# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20160403_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='favorites',
            field=models.BooleanField(default=False),
        ),
    ]
