# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_notes_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='id',
            field=models.UUIDField(default='1a5ec694d93e49ef85a4f692475d7603', editable=False, primary_key=True, serialize=False),
        ),
    ]
