# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20160403_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='id',
            field=models.UUIDField(default=137240376974649, editable=False, primary_key=True, serialize=False),
        ),
    ]
