# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20160403_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='slug',
        ),
        migrations.AlterField(
            model_name='notes',
            name='id',
            field=models.UUIDField(default='0a95fba6f93f11e5a9657cd1c3eb1d39', editable=False, primary_key=True, serialize=False),
        ),
    ]
