# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_auto_20160403_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='id',
            field=models.UUIDField(default='92dbabe6f98211e5876500e04d68034f', editable=False, primary_key=True, serialize=False),
        ),
    ]
