# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_auto_20160403_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='id',
            field=models.UUIDField(default='dbd16380f98311e5adf900e04d68034f', editable=False, primary_key=True, serialize=False),
        ),
    ]
