# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_auto_20160403_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='id',
            field=models.CharField(default='8ef15b00f98411e5a2b200e04d68034f', editable=False, max_length=15, primary_key=True, serialize=False),
        ),
    ]
