# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 16:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0014_auto_20160404_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='favorites',
        ),
        migrations.AddField(
            model_name='notes',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
