# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0015_auto_20160406_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='favorites',
        ),
        migrations.AddField(
            model_name='notes',
            name='favorites',
            field=models.BooleanField(default=False),
        ),
    ]
