# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 09:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0016_auto_20160406_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='date',
        ),
        migrations.AddField(
            model_name='notes',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 13, 9, 21, 45, 503500, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 13, 9, 21, 47, 798113, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
